default_connection_name = "SF_Dinesh2012"

[SF_Dinesh2012]
account = "MQB13207"
user = "ADMIN"
password = "Din143@cortex1"
database = "DOC_CHATBOT_DB"
schema = "PUBLIC"
warehouse = "DOC_CHATBOT_WH"
role = "ACCOUNTADMIN"

